name: Deploy to ECR (Database Only)

on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build and Push Database Image
    runs-on: ubuntu-latest

    steps:

    # Step 1: Check out code
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    # Step 3: Build, tag, and push the database image to Amazon ECR
    - name: Build, tag, and push database image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        DB_REPOSITORY: clo835-assignment1-db
        IMAGE_TAG: latest
      run: |
        # Build and push MySQL database image
        docker build -t $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG
