name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:

    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    # Step 3: Build, test, tag, and push image to Amazon ECR
    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: clo835-assignment1-app  # Update this based on your repository
        IMAGE_TAG: v0.2
      run: |
        cd Chapter02/kubia/
        ls -ltra
        # Build the Docker image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Run and test the Docker container
        docker run -d -p 80:8080 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let the container start"
        sleep 10
        curl localhost -vvv
        # Push the Docker image to Amazon ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
